language: node_js
node_js:
- 8.10.0
script:
  - npm test
after_script:
- scp -o StrictHostKeyChecking=no ./app.js root@101.200.37.231:/root/code
before_install:
- openssl aes-256-cbc -K $encrypted_7ca871ec14ed_key -iv $encrypted_7ca871ec14ed_iv
 -in langlong3000_rsa.enc -out ~/.ssh/langlong3000_rsa -d



- chmod 600 ~/.ssh/langlong3000_rsa

- eval $(ssh-agent)
- ssh-add ~/.ssh/langlong3000_rsa

